name: service_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.0
  path_provider: ^2.0.2
  sqflite: ^2.3.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.5
  toggle_switch: ^2.1.0
  auto_size_text: ^3.0.0
  colorful_safe_area: ^1.0.0
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  go_router: ^13.0.1
  sliding_clipped_nav_bar:
    git:
      url: https://github.com/Dr4gnSt4lk/sliding_clipped_nav_bar
  flutter_native_splash: ^2.3.9
  flutter_multi_formatter: ^2.12.4
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  dots_indicator: ^3.0.0
  loop_page_view: ^1.2.5
  table_calendar: ^3.1.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
      - icons/
      - banners/
      - jobs/
